[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[build]
  command = "npm run build"
  publish = "dist"

# (необязательно) укажите версию Node и переменные окружения.
# Их также можно задать в Netlify → Site settings → Environment.
[build.environment]
  NODE_VERSION = "20"
  # VITE_API_URL = "https://kitsu.io/api/edge"

# SPA-редирект для React Router: все пути отдаются index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Рекомендуемые заголовки кэширования для ассетов Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Можно добавить заголовки для index.html, чтобы он не кэшировался слишком агрессивно
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"


